apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mindbox-scale-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "update", "patch"]